version: '3.4'
services:
  notebook:
    image: jupyter/base-notebook:latest
    container_name: my-notebook
    hostname: my-notebook
    command:
      - start-notebook.sh
      - --NotebookApp.token='' # 認証を無効化
      - --NotebookApp.disable_check_xsrf=True # CSRFチェックを無効化
      - --notebook-dir='work' # ログイン時のカレントディレクトリを変更
    ports:
      - 8888:8888
    volumes:
      - ./data:/home/jovyan/work
    networks:
      - default
      - my-network
networks:
  my-network:
    external: true
